name: CI

on:
  pull_request:
    branches:
    - master
    paths-ignore:
    - 'README.md'
    - 'LICENSE'
    - 'CODE_OF_CONDUCT.md'
    - 'CONTRIBUTING.md'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Ruby 2.6
      uses: actions/setup-ruby@v1
      with:
        ruby-version: "2.6"
    - uses: actions/cache@v2
      with:
        path: vendor/bundle
        key: ${{ runner.os }}-gems-${{ hashFiles('**/Gemfile.lock') }}
        restore-keys: |
          ${{ runner.os }}-gems-
    - run: gem install bundler
    - run: bundle config path vendor/bundle
    - run: bundle install --jobs 4 --retry 3


#   test:
#     runs-on: ubuntu-latest

#     steps:
#       - uses: actions/checkout@v2.0.0
#         with:
#           fetch-depth: 1

#       - name: Set env
#         run: echo ::set-env name=workspace::$GITHUB_WORKSPACE

#       - uses: ruby/setup-ruby@master
#         with:
#           ruby-version: ${{ env.RUBY_VERSION }}

#       - name: Recover Ruby dependency cache
#         uses: actions/cache@v1
#         with:
#           path: ./vendor/bundle
#           key: ${{ runner.OS }}-rubydeps-${{ hashFiles('Gemfile.lock') }}
#           restore-keys: |
#             ${{ runner.OS }}-rubydeps-${{ env.cache-name }}-
#             ${{ runner.OS }}-rubydeps-
#             ${{ runner.OS }}-

#       - name: Install Ruby deps
#         run: |
#           gem install bundler:2.1.4
#           bundle install --path vendor/bundle --jobs 4 --retry 3

#       - name: Lint and Rubocop
#         run: |
#           bundle exec rubocop
#           bundle exec erblint app/{cells,views}/**/*.erb